### ISSUE TITLE
[Chapter 1] Tracking Issue

### ISSUE THREAD

**Issue by leeexyz** [openmlsys/openmlsys-zh#104]
#### 1.1 机器学习应用
- [ ] 监督学习是已知输入输出对应关系情况下的学习，**_比如_** 给定输入图像和它对应的内容标签，**_则学习图像分类_**（Classification）;
       **建议**：监督学习是已知输入输出对应关系情况下的学习，**_比如：_** 给定输入图像和它对应的内容标签，**_学习图像分类_**（Classification）;
- [ ] 强化学习则是给定一个学习环境和任务目标，算法自主地去不断尝试、改进自己、以实现任务目标 **_。比如_** AlphaGo围棋就是用强化学习实现的，给定的环境是围棋的规则、而目标则是胜利得分。
       **建议**：强化学习则是给定一个学习环境和任务目标，算法自主地去不断尝试、改进自己、以实现任务目标 **_，比如：_** AlphaGo围棋就是用强化学习实现的，给定的环境是围棋的规则、而目标则是胜利得分。
- [ ] 虽然机器学习算法很多，但无论是经典算法还是深度学习算法的计算往往以向量、矩阵运算为**主体的**，因此本书主要通过深度神经网络为例子展开机器学习系统的介绍。
       **建议**：矩阵运算为**主体**。
- [ ] 从应用领域上划分...这一段开始，一些专业名词没有加对应英文，和其他段落不一致。

#### 1.2 机器学习系统的需求
- [ ] 图1.2.1中的 **_机器学习框架部分_** 存在几个问题。第一：例如后面的 **_冒号_** 与下面一个不一致，这里应该是写成英文的了；第二：每个框架后面的逗号也是英文的。
- [ ] 图1.2.1的标题从 **_机器学习框架_**  改为 **_机器学习系统_** 更加准确？这个图是包含了三部分：应用，框架和硬件（处理器），但是标题没有反应出来。
- [ ] **Self-attention Neural Networks** 改为 **_Self-Attention ..._** 字母大写。
- [ ] 在设计机器学习框架的过程，.. 这里少了一个字，应改为 **_的过程中_**。

#### 1.4 适用读者

未完待续...

**Comment by eedalong** [comment]
Great，我们有一个amazing社区

**Comment by luomai** [comment]
@leeexyz 非常感谢。你可以考虑直接提交一个PR来修正这些，也可以我来起PR来改。你希望哪一种？

**Comment by leeexyz** [comment]
@luomai 那我直接提PR一起来修正 :)

**Comment by luomai** [comment]
我其实正在更新README，今晚会提交一个PR。你可以看看我更新后的版本。

**Comment by luomai** [comment]
Fixed.

**Comment by 13218011661** [comment]
您获得了我们书籍检视的奖励，麻烦在5月15日前，在此贴回复一下邮箱哦

**Comment by ZRFBelong** [comment]
***@***.***
谢谢，辛苦了

**Comment by luomai** [comment]
@leeexyz
